name: Integration_tests
on:
  push:
    branches: [ master, testing-ffi]
    paths:
      - '**'
      - '!README.md'
  pull_request:
    branches: [ master ]
    paths:
      - '**'
      - '!README.md'
defaults:
  run:
    working-directory: example

jobs:
  android_test:
    name: Android_test
    runs-on: macos-latest
    strategy:
      matrix:
        # api-level: [21, 23, 24, 26, 28, 29]
        api-level: [29]
        target: [google_apis]
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: cd example && flutter pub get && flutter test integration_test
  
          
  ios_test:
    name: iOS_test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 8'
      - run: flutter pub get
      - name: Run integration tests
        run: flutter test integration_test
